### ISSUE TITLE
Repo missing a license

### ISSUE THREAD

**Issue by fleuronvilik** [john-smilga/react-projects#10]
Hi @john-smilga!

Thank you for the React tutorial.
I almost finished it and even started building some of the related projects.

I know the setups are meant to be used as starting point. But unless you add a [license](https://choosealicense.com/) that grants us such permissions, we may not use, modify and/or share them.

This is also the case of [react-basics-2020](https://github.com/john-smilga/react-basics-2020) and [react-advanced-2020](https://github.com/john-smilga/react-advanced-2020).

**Comment by john-smilga** [comment]
Yeah, i'm not sure what to say apart from, you are overthinking it.

**Comment by DVC57** [comment]
I just started my lessons with your videos... am really grateful, even though it's watch and paste. it seems the videos are been uploaded in 2020 cause I cant find the links again. @john-smilga
