### ISSUE TITLE
on 15 project 

### ISSUE THREAD

**Issue by venkat-gitwork** [john-smilga/react-projects#26]
hi i am learning with your 15 projects . there i faced issue in render data using url's .

for example in 6-tab , after loading nd setJobs . i print in console , i got empty array twice nd 4 times data .
i ignore that after doing full 6-tab project similar way you did when i check data is empty while printing in console .

kindly help me to clear my confusion and to go forward .. 
![issue](https://user-images.githubusercontent.com/81239452/112150415-11210080-8c06-11eb-8a73-9a3e284c710d.png)

**Comment by john-smilga** [comment]
Hello,
I'm sorry but I don't completely understand your question.
Also, git repo issues is not for asking video questions. 
For course related questions, please utilize course Q&A for the questions.
