### ISSUE TITLE
Project 8 Lorem Ipsum Setup

### ISSUE THREAD

**Issue by narbota** [john-smilga/react-projects#29]
The final project looks different from the video. The counter has negative numbers and in the video, the counter has positive.[
<img width="780" alt="Screen Shot 2021-04-12 at 11 53 11 AM" src="https://user-images.githubusercontent.com/10549326/114424436-1b3f7a80-9b86-11eb-8706-88525b8028f2.png">
<img width="1080" alt="Screen Shot 2021-04-12 at 11 54 09 AM" src="https://user-images.githubusercontent.com/10549326/114424463-21355b80-9b86-11eb-9989-3bce380b8fd5.png">

**Comment by AkashKumar2701** [comment]
Issur Fixed !!
