### ISSUE TITLE
Need clarification - 02: Tours

### ISSUE THREAD

**Issue by Lbhagi** [john-smilga/react-projects#30]
While removing tours, I called {fetchTours()} on refresh button instead of {fetchTours}

Then I see Loading.. and the list of tours displayed. It supposed to be Refresh button and text as "No Tours Left". If I click refresh then all tours has to be displayed.

Can you explain difference between calling fetchTours vs fetchTours() onclick event of Refresh button?

**Comment by Chronoviser** [comment]
{fetchTours} waits for you to click the button, then it calls fetchTours()
But
{fetchTours()} calls fetchTours() as soon as this statement is compiled, and doesn't depend on the user to click the button.
