### ISSUE TITLE
Websites images

### ISSUE THREAD

**Issue by JealousGx** [john-smilga/react-projects#36]
https://react-projects.netlify.app
In the above website, the websites are collectively shared. I wanted to know if the shared websites' images were taken manually or there is something going on in the backend that automatically takes the images and posts them here. Like in the image below, netlify is actually taking pictures automatically from the published websites:

![image](https://user-images.githubusercontent.com/59867217/119329279-e66d1b80-bc39-11eb-8734-330ddd71f080.png)

**Comment by AkashKumar2701** [comment]
In These Projects The Link To These Images Is Already Stored In Some Files Wherever They Are Being Used. When The Code Compiles The Image Is Automatically Picked Up From The Website Which Is Mentioned And Gets Displayed In This Website.

Let Me Show You An Example

![Screenshot (46)](https://user-images.githubusercontent.com/65177696/130615407-7089a354-01d3-47df-8d11-592604c045e4.png)


Please Let Me Know If Your Doubt Is Cleared Or Not..✌✌
