### ISSUE TITLE
How to tweak the slider code

### ISSUE THREAD

**Issue by dendigital** [john-smilga/react-projects#4]
How can I tweak the slider so I can see 2-3 slides with 'nextSlide' class beside 'activeSlide'?

For example: 

active slide | next slide 1 | next slide 2 and then slide 1 becomes active and new one comes in to view (next slide 3)

**Comment by Haroonabdulrazaq** [comment]
You need to display them in your render but you'll have to make only one active.
For example if you need a counter you can use to track the active slide then counter - 1 would be the one on the left of the active slide and counter + 1 would be on the right of the counter. you can use CSS to show there rank(hierarchy) like using z-index.
So when you click next it increases your counter by one, to the one showing on the former right, then your former active slide becomes the new left. 
Same when you click previous the counter decreases by one, your former active slide becomes the new right and the former left becomes the active slide.

Don't forget to make the slides wrap, Don't forget to check the prevState of counter in your handlePrev, and handleNext function
