### ISSUE TITLE
09-color-generator is missing values.js

### ISSUE THREAD

**Issue by NeoTechni** [john-smilga/react-projects#60]
App.js imports Values from values.js, which can't be found

**Comment by john-smilga** [comment]
It looks like you did not  watch corresponding video. There are no resources missing.

**Comment by NeoTechni** [comment]
I was watching your 10 hour react course
https://www.youtube.com/watch?v=iZhV0bILFb0

But it doesn't cover this repo at all.

**Comment by oyinakin** [comment]
npm install values.js
